apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # or "ReadOnlyMany", "ReadWriteMany", "ReadWriteOncePod"
  persistentVolumeReclaimPolicy: Retain # or "Recycle", "Delete"
  storageClassName: ""
  hostPath:
    path: /tmp/data