apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # or "ReadOnlyMany", "ReadWriteMany", "ReadWriteOncePod"
  persistentVolumeReclaimPolicy: Delete # or "Recycle", "Delete"
  storageClassName: ""
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce # or "ReadOnlyMany", "ReadWriteMany", "ReadWriteOncePod"
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
